use_frameworks!

platform :ios, '13.0'

target 'AScenesKit_Example' do
  pod 'AScenesKit', :path => '../'
  pod 'AUiKit', :path => '../../AUiKit'
  pod 'AgoraRtcEngine_iOS', :path => './libs'
  pod 'AgoraLyricsScore', '1.1.1-beta-3'

  target 'AScenesKit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
