source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '13.0'

target 'AUIKaraoke' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'AScenesKit', :path => '../AScenesKit'
  pod 'AgoraRtcEngine_Special_iOS', '4.1.1.20'
#  pod 'AUIKitCore', :path => '../../../AUIKit'
#  pod 'AgoraLyricsScore', '1.1.1-beta-3'
#  pod 'LookinServer', :configurations => ['Debug']
#  pod 'SwiftLint'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end
