spring:
    application:
        # Application name
        name: uikit-karaoke
    data:
        # MongoDB configuration
        mongodb:
            uri: mongodb://admin:admin@localhost:27017/test
    # Redis configuration
    redis:
        database: 0
        host: localhost
        lettuce:
            # Pool
            pool:
                max-active: 100
                max-wait: -1
                max-idle: 50
                min-idle: 10
        password: admin
        port: 6379
        timeout: 3000

# Log
log:
    level: info
    path: ./logs
# Metric
# http://127.0.0.1:9090/metrics/prometheus
management:
    server:
        port: 9090
    endpoint:
        health:
            show-details: always
        prometheus:
            enabled: true
    endpoints:
        web:
            exposure:
                include: "*"
            base-path: /metrics
# Process RTC channel event
# refer to https://docs.agora.io/cn/video-call-4.x/rtc_channel_event?platform=All%20Platforms
ncs:
    secret:
# Scheduled tasks
task:
    # Scheduled updating of room status
    updateRoomStatusQueueCron: 0/15 * * * * ?
# RTC/RTM token
token:
    appId:
    appCertificate:
    expirationInSeconds: 86400
    privilegeExpirationInSeconds: 86400

# IM
em:
    auth:
        appKey:
        clientId:
        clientSecret:
    chatRoom:
        maxUsers: 1000

