# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '13.0'

target 'AUiKaraokeApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'AScenesKit', :path => '../../AScenesKit'
  pod 'AUiKit', :path => '../../AUiKit'
  pod 'AgoraRtcEngine_iOS', :path => './libs'
  pod 'AgoraLyricsScore', '1.1.1-beta-3'

end
